### ISSUE TITLE
Cube Info

### ISSUE THREAD

**Issue by TonyFrend** [rmountjoy92/VectorCloud#10]
Not sure if one of the recent updates has broken the Cube Info functionality.

No cube information is displayed (see attached Word file).

I can connect to the Cube via the Anki Vector app.

Best regards,

Tony
[Cube Info.docx](https://github.com/rmountjoy92/VectorCloud/files/2738326/Cube.Info.docx)

**Comment by rmountjoy92** [comment]
it's crazy unreliable with the SDK lol
