### ISSUE TITLE
Package is missing from Requirements file

### ISSUE THREAD

**Issue by krconv** [rmountjoy92/VectorCloud#12]
I believe that these two packages are missing from the `requirements.txt`.

```
grpcio
grpcio-tools
```

Without `grpcio`, I got this error:
```python
  File "/app/vectorcloud/main/utils.py", line 6, in <module>
    from grpc._channel import _Rendezvous
ModuleNotFoundError: No module named 'grpc'
```

And without `grpcio-tools`, I got this error:
```python
  File "/app/vectorcloud/main/utils.py", line 6, in <module>
    from grpc._channel import _Rendezvous
ImportError: No module named _channel
```

**Comment by rmountjoy92** [comment]
Both grpcio and grpcio-tools are dependencies of the Anki Vector SDK. If you installed the SDK as per Anki's instructions and verified that it works as per the installation instructions on VectorCloud's readme, both packages should be on your machine.

**Comment by krconv** [comment]
I did end up installing the `anki_vector` package, but I hit these errors before realizing that I also needed the SDK to be installed (I was installing these into a Docker container, so I didn't have the SDK set up yet).
I guess it isn't as big of a deal then. I didn't realize that we are still implicitly relying on these packages through the `anki_vector` package

**Comment by krconv** [comment]
Understood, no problem. I think best practice would be to include `anki_vector`, `grpcio`, `grpcio-tools` in the `requirements.txt`, because you `import` them all, although I don't think it makes much of a difference.
