### ISSUE TITLE
Say Option in the api

### ISSUE THREAD

**Issue by ItsWolfiePlaysMC** [rmountjoy92/VectorCloud#19]
Please add a Say Option in the api
**Example:** localhost:5000/api/say&msg=msghere

(It makes Vector Say Something)

**Comment by rmountjoy92** [comment]
Install the application 'Say Text' from the app store, then go to:
```
localhost:5000/api/modrun/Say-Text/text_to_say=msghere%
```
I'd prefer to do the api functions through the application system to make it more modular, instead of adding a bunch of api resources.
