### ISSUE TITLE
Docker Error on Raspberry Pi

### ISSUE THREAD

**Issue by onlyspike** [rmountjoy92/VectorCloud#22]
Hi,

Just tried to run docker on Raspberry Pi, but got the bellow error.

standard_init_linux.go:207: exec user process caused "exec format error"

Any idea what this means?

**Comment by rmountjoy92** [comment]
Installing the Vector SDK in docker on RPI does not work. It's because there isn't a version of opencv for ARM processors that satisfies the dependency. To get the Vector SDK working on an RPI, you'll have to follow the guide here: https://forums.anki.com/t/vector-sdk-install-on-raspberry-pi/27541

**Comment by onlyspike** [comment]
I have already followed those steps and got the sdk working my on Pi however cant get VectorCloud working. from either docker or installation.
