### ISSUE TITLE
Same error on linux or windows

### ISSUE THREAD

**Issue by jesterino** [rmountjoy92/VectorCloud#4]
Hello 
got a GRPC module not found both on debian and windows10

J:\Users\gianfranco\Desktop\VectorCloud-master>py run.py
C:\Users\gianfranco\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask_sqlalchemy\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from vectorcloud import app
  File "J:\Users\gianfranco\Desktop\VectorCloud-master\vectorcloud\__init__.py", line 17, in <module>
    from vectorcloud.main.routes import main
  File "J:\Users\gianfranco\Desktop\VectorCloud-master\vectorcloud\main\routes.py", line 11, in <module>
    from vectorcloud.main.utils import robot_do, get_stats
  File "J:\Users\gianfranco\Desktop\VectorCloud-master\vectorcloud\main\utils.py", line 6, in <module>
    from grpc._channel import _Rendezvous
**ModuleNotFoundError: No module named 'grpc'**

**Comment by jesterino** [comment]
Solved installing grpc with:
python -m pip install grpcio

Now i got this:

C:\Users\gianfranco\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask_sqlalchemy\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Cannot import from anki_vector: Install per Anki instructions

Did i need Anki Vector SDK ? i don't had it from bracket pre-release.
Thank you

**Comment by rmountjoy92** [comment]
from the how to run on the readme:
- Install the SDK as per the directions in the SDK docs.

https://developer.anki.com/vector/docs/initial.html

**Comment by macfly1202** [comment]
HI , install 
$ python -m pip install grpcio
$ python -m pip install grpcio-tools

then 
follow Anki vector install steps here : https://developer.anki.com/vector/docs/install-linux.html

Working for me
