### ISSUE TITLE
Build number of VectorCloud on the apps home page

### ISSUE THREAD

**Issue by TonyFrend** [rmountjoy92/VectorCloud#7]
Would it be worth adding the build number of VectorCloud to the apps home page (perhaps below the SDK version number?) so that it is easier to confirm that the update has gone as expected and also to aid troubleshooting of bugs etc. ?

I find this information very useful for other GitHub apps.

Best regards,

Tony

**Comment by rmountjoy92** [comment]
Hey Tony! 

I was waiting until I made an update system to start naming versions, but the release I'm currently working will implement version numbers, once released you will find VectorCloud's version number on the update page. 

Thanks for you suggestions and for using VectorCloud!!
